### ISSUE TITLE
Text going outside of the tooltip

### ISSUE THREAD

**Issue by DannyDTenacious** [defenseunicorns/uds-runtime#293] opened 2024-09-06 22:26 UTC
### Environment

Device and OS: Macbook (Venture 13.4.1)
Browser: Firefox (not reproducible in chrome)

### Steps to reproduce

1. Select Monitor/Pepr
2. Look for a "Mutated" policy in the table
3. Hover over "Details" to trigger the tooltip to appear

### Expected result
All text should fit inside the tooltip

### Actual Result
Text continues outside the tooltip (see screenshot)

### Visual Proof (screenshots, videos, text, etc)
<img width="1105" alt="Screenshot 2024-09-06 at 5 23 31 PM" src="https://github.com/user-attachments/assets/4e1f5ebc-a118-4e7c-a747-4e4ebaa134cd">
<img width="514" alt="Screenshot 2024-09-06 at 5 23 40 PM" src="https://github.com/user-attachments/assets/f7752c04-b716-429d-aa4d-8e1065463878">

**Comment by decleaver** [comment] 2024-09-16 19:32
Chatted with @DannyDTenacious, looks like this might be a firefox specific issue. Was not able to reproduce on chrome when looking at the exact same data

**Comment by BillyFigueroa** [comment] 2024-09-23 18:07
@DannyDTenacious check this out tomorrow when we release tonight. Should be fixed. I had a version of FF that could reproduce and I believe I fixed it

**Closed** 2024-09-23 18:06 UTC
Labels: possible-bug
